const assert=require('node:assert/strict');
const {DatabaseSync}=require('node:sqlite');
const fs=require('node:fs');
(async()=>{
 const {handlePetRequest}=await import('../cloud-save/worker.mjs');
 const {freshPet,changePet,energyNow,normalizePet,grantPoints}=await import('../pet/state.mjs');
 const {dayKey}=await import('../pet/rules.mjs');
 const sql=new DatabaseSync(':memory:');sql.exec(fs.readFileSync(require('node:path').join(__dirname,'../cloud-save/schema.sql'),'utf8'));
 const DB={prepare(query){return {bind(...args){return {async first(){return sql.prepare(query).get(...args)},async run(){const r=sql.prepare(query).run(...args);return {meta:{changes:Number(r.changes)}}}}}}}};
 const token='a'.repeat(48),other='b'.repeat(48),pin='724681';let id=0,revision=0;
 async function send(body,key=token,origin='https://hugfeature.github.io'){
   const response=await handlePetRequest(new Request('https://test.invalid/api/pet',{method:body?'POST':'GET',headers:{Authorization:'Bearer '+key,Origin:origin},body:body?JSON.stringify({requestId:(++id).toString(16).padStart(32,'0'),revision,...body}):undefined}),{DB});
   const data=await response.json();if(key===token&&data.revision)revision=data.revision;
   assert.equal(JSON.stringify(data).includes('"_parent"'),false,'private PIN verifier must never leave server');
   assert.equal(JSON.stringify(data).includes('"hash"'),false);
   return {status:response.status,body:data,headers:response.headers};
 }
 assert.equal((await send()).status,404);
 let a=await send({action:'adopt'});assert.equal(a.status,200);assert.equal(a.body.pet.points,0);
 assert.equal((await send({action:'feed',value:'apple'})).status,400,'no free paid actions');
 assert.equal((await send({action:'parentAward',value:{task:'homework'},pin})).status,400,'parent setup required');
 a=await send({action:'parentSetup',pin});assert.equal(a.status,200);assert.equal(a.body.pet.parentConfigured,true);
 assert.equal((await send({action:'parentSetup',pin:'999999'})).status,400,'cannot replace parent PIN');
 a=await send({action:'parentAward',pin:'123456',value:{task:'homework'}});assert.equal(a.status,401);assert.equal(a.body.pet.points,0);
 const award={action:'parentAward',pin,value:{task:'homework'},requestId:'d'.repeat(32),revision};
 a=await send(award);assert.equal(a.body.pet.points,20);
 a=await send(award);assert.equal(a.body.pet.points,20,'retries do not double-award');
 assert.equal((await send({action:'parentAward',pin,value:{task:'homework'}})).status,400,'one task award per day');
 const beforeFeed=revision,feed={action:'feed',value:'apple',revision,requestId:'c'.repeat(32)};
 a=await send(feed);assert.equal(a.body.pet.food,97);assert.equal(a.body.pet.points,15);assert.equal(a.body.pet.care,1);
 a=await send(feed);assert.equal(a.body.pet.points,15,'retries do not double-charge');
 a=await send({action:'bath',revision:beforeFeed});assert.equal(a.status,409);assert.equal(a.body.pet.points,15);
 a=await send({action:'bath'});assert.equal(a.body.pet.points,7);assert.equal(a.body.pet.clean,100);
 assert.equal(a.body.pet.activity.action,'bath');const bathId=a.body.pet.activity.id;assert.equal((await send()).body.pet.activity.id,bathId,'redeemed interaction survives another device read');
 assert.equal((await send({action:'count'})).status,400,'finish or resume already redeemed activity first');
 assert.equal((await send({action:'finish',value:'not-my-activity'})).status,400);
 a=await send({action:'finish',value:bathId});assert.equal(a.body.pet.points,7);assert.equal(a.body.pet.activity,null);
 assert.equal((await send({action:'memory'})).status,400,'cannot overspend');
 a=await send();assert.equal(a.body.pet.points,7,'another phone reads authoritative balance');
 assert.equal(a.body.pet.ledger[0].amount,-8);
 assert.equal((await send({action:'parentAward',pin,value:{task:'custom',points:0,reason:'test'}})).status,400);
 a=await send({action:'parentAward',pin,value:{task:'custom',points:30,reason:'整理书包'}});assert.equal(a.body.pet.points,37);
 for(const action of ['play','count','memory']){a=await send({action});assert.equal(a.status,200);a=await send({action:'finish',value:a.body.pet.activity.id});assert.equal(a.status,200)}
 assert.equal(a.body.pet.points,5);assert.equal(a.body.pet.totalPoints,50,'games never mint points');
 a=await send({action:'pet'});assert.equal(a.body.pet.points,5,'cuddle is free');
 a=await send({action:'sleep'});assert.equal(a.body.pet.points,5);assert.equal((await send({action:'feed',value:'apple'})).status,400);
 a=await send({action:'wake'});assert.equal(a.body.pet.points,5,'rest never mints points');
 assert.equal((await send(undefined,other)).status,404);
 a=await send({action:'adopt'},other);assert.equal(a.body.pet.points,0);assert.equal(a.body.pet.parentConfigured,false);
 assert.equal((await send(undefined,'bad')).status,401);assert.equal((await send(undefined,token,'https://evil.invalid')).status,403);
 for(let i=0;i<5;i++)assert.equal((await send({action:'parentAward',pin:'000000',value:{task:'reading'}})).status,401);
 assert.equal((await send({action:'parentAward',pin,value:{task:'reading'}})).status,429,'rate limit enforced even with correct PIN during lock');
 const now=Date.parse('2026-09-27T15:59:59Z');
 const rewarded=grantPoints(freshPet(),{task:'homework'},now);
 assert.throws(()=>grantPoints(rewarded,{task:'homework'},now));
 assert.equal(grantPoints(rewarded,{task:'homework'},now+2000).points,40,'Shanghai midnight resets tasks, not balance');
 assert.equal(dayKey(now),'2026-09-27');assert.equal(dayKey(now+2000),'2026-09-28');
 const sleeping=changePet(freshPet(),'sleep',null,100000);assert.equal(energyNow(sleeping,109000),100);
 assert.equal(changePet(sleeping,'wake',null,109000).points,0);
 assert.equal(energyNow(sleeping,99000),75);assert.deepEqual(normalizePet(null),freshPet());
 assert.equal(normalizePet({care:8,food:99}).care,8,'legacy progress survives migration');
 assert.equal(normalizePet({care:8,food:99}).points,0);
 sql.close();console.log('PASS: parent PIN/setup/lockout, task awards, custom rewards, no child minting, exchange debits, insufficient balance, retry idempotency, stale-write protection, cross-device read, family isolation, Shanghai day rollover, legacy saves and free sleep.');
})().catch(e=>{console.error(e);process.exitCode=1});
