import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFileSync} from 'node:fs';
import * as state from '../pet/state.mjs';
import * as rules from '../pet/rules.mjs';
import * as connection from '../pet/connection.mjs';
const elements=new Map(),events=new Map(),requests=[];let copied='';
function el(id){if(!elements.has(id))elements.set(id,{textContent:'',open:false,classList:{toggle(){},add(){},remove(){}},addEventListener(){},querySelector(){return el('child')},querySelectorAll(){return []},focus(){},select(){},setAttribute(){},showModal(){this.open=true}});return elements.get(id)}
const context=vm.createContext({...state,...rules,...connection,console,URL,AbortController,Date,Number,crypto:globalThis.crypto,setTimeout,clearTimeout,setInterval(){},location:{hostname:'terminal.local',origin:'http://terminal.local',hash:''},navigator:{onLine:true,clipboard:{async writeText(s){copied=s}}},window:{addEventListener(n,cb){events.set(n,cb)}},document:{hidden:false,body:el('body'),getElementById:el,querySelectorAll(){return []},addEventListener(n,cb){events.set(n,cb)}},fetch:async(url,opts)=>{requests.push(opts);return {ok:true,json:async()=>({revision:2,pet:state.freshPet()})}}});
const source=readFileSync(new URL('../pet/pet.js',import.meta.url),'utf8').replace(/^import .*;\n/gm,'').replace(/^init\(\);$/m,'');
vm.runInContext(source+`\nrender=()=>{};renderConnection=()=>{};token='${'a'.repeat(48)}';ready=true;revision=1;`,context);
const run=s=>vm.runInContext(s,context),settle=()=>new Promise(resolve=>setImmediate(resolve));
el('speech').textContent='继续找颜色吧';
events.get('visibilitychange')();await settle();
assert.equal(requests.length,1);assert.equal(el('speech').textContent,'继续找颜色吧','automatic foreground sync preserves pet dialogue');
events.get('visibilitychange')();events.get('online')();await settle();assert.equal(requests.length,1,'brief returns and online events are deduplicated');
run("lastNetworkAttempt=0;mode='game'");events.get('visibilitychange')();await settle();assert.equal(requests.length,1,'active game is not interrupted');
run("mode='';dialog.open=true");events.get('online')();await settle();assert.equal(requests.length,1,'open dialog is not interrupted');
run("dialog.open=false");await el('reconnectNow').onclick();assert.equal(requests.length,2,'manual retry remains available immediately');assert.notEqual(el('speech').textContent,'继续找颜色吧');
run("pending={action:'bath',revision:2,requestId:'same-request'};ready=false;lastNetworkAttempt=0");el('speech').textContent='原来的提示';events.get('online')();await settle();assert.equal(requests.at(-1).method,'POST');assert.equal(JSON.parse(requests.at(-1).body).requestId,'same-request');assert.equal(el('speech').textContent,'原来的提示');assert.equal(run('pending'),null);
el('shareTop').onclick();await el('copyLink').onclick();assert.equal(copied,connection.familyLink('a'.repeat(48)));await el('copyPublic').onclick();assert.equal(copied,connection.FAMILY_PAGE);assert.equal(new URL(copied).hash,'');
console.log('PASS: silent foreground sync, deduplication, game/dialog protection, manual retry, same-request recovery, distinct family/public sharing.');
