const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http');
const {chromium}=require('playwright');
(async()=>{const server=http.createServer((q,r)=>{r.setHeader('Content-Type','text/html;charset=utf-8');r.end(fs.readFileSync(process.env.RACER_TEST_SOURCE||path.join(__dirname,'../index.html')))});await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;
try{browser=await chromium.launch({headless:true,...(process.env.TEST_BROWSER_PATH?{executablePath:process.env.TEST_BROWSER_PATH,args:['--no-sandbox','--disable-gpu','--disable-dev-shm-usage']}:{})});const p=await browser.newPage({viewport:{width:390,height:640},isMobile:true,hasTouch:true});const errors=[];p.on('pageerror',e=>errors.push(e.message));await p.addInitScript(()=>{window.speechSynthesis=undefined;window.SpeechSynthesisUtterance=undefined;let time=0,q=[];performance.now=()=>time;requestAnimationFrame=f=>q.push(f);window.advance=ms=>{while(ms>0){const n=Math.min(40,ms);ms-=n;time+=n;const run=q;q=[];run.forEach(f=>f(time))}}});await p.goto(`http://127.0.0.1:${server.address().port}`);
await p.locator('#listenTask').click();await p.waitForFunction(()=>document.getElementById('taskVoice').currentTime>.2,null,{polling:100});assert(await p.evaluate(()=>document.getElementById('taskVoice').duration>10),'actual bundled audio did not decode');await p.locator('#listenTask').click();assert(await p.evaluate(()=>document.getElementById('taskVoice').paused));await p.locator('#listenTask').click();await p.waitForFunction(()=>!document.getElementById('taskVoice').paused,null,{polling:100});await p.locator('#sound').click();assert(await p.evaluate(()=>document.getElementById('taskVoice').paused),'mute did not stop narration');
for(const height of [500,640,844])for(const track of [0,1,2]){await p.setViewportSize({width:390,height});await p.locator('#settings').click();await p.locator(`#modal [data-track="${track}"]`).click();await p.locator('#closeModal').click();await p.locator('#start').click();await p.evaluate(()=>advance(3500));
for(const direction of ['ArrowLeft','ArrowRight']){await p.keyboard.down(direction);await p.evaluate(()=>advance(3000));await p.keyboard.up(direction);const g=await p.evaluate(()=>{const c=document.getElementById('game'),w=c.width,h=c.height,d=c.getContext('2d').getImageData(0,0,w,h).data;let wheels=0,bad=0,rows=[];for(let y=Math.floor(h*.55);y<Math.floor(h*.86);y++){let roadMin=w,roadMax=-1,carMin=w,carMax=-1;for(let x=0;x<w;x++){const i=(y*w+x)*4,r=d[i],g=d[i+1],b=d[i+2];for(const yy of [y-1,y,y+1]){const j=(yy*w+x)*4,rr=d[j],gg=d[j+1],bb=d[j+2];if(rr>=95&&rr<=140&&gg-rr>=13&&gg-rr<=26&&bb-rr>=8&&bb-rr<=25){roadMin=Math.min(roadMin,x);roadMax=x}}if(r===32&&g===46&&b===50){carMin=Math.min(carMin,x);carMax=x;wheels++}}if(carMax>=0&&(carMin<roadMin||carMax>roadMax)) {bad++;rows.push({y,carMin,carMax,roadMin,roadMax})}}return{wheels,bad,rows}});assert(g.wheels>10,'racing wheels not rendered');if(g.bad&&process.env.QA_SHOTS)await p.screenshot({path:path.join(process.env.QA_SHOTS,'edge-failure.png')});assert.equal(g.bad,0,`wheel outside asphalt: ${height}/${track}/${direction}: ${JSON.stringify(g)}`)}
if(process.env.QA_SHOTS&&height===640&&track===1)await p.screenshot({path:path.join(process.env.QA_SHOTS,'racer-edge.png')});await p.locator('#pause').click();await p.locator('#garage').click()}
assert.deepEqual(errors,[]);console.log('PASS: bundled narration decodes/plays without speech API, replay/stop/mute; full wheels inside asphalt at both steering limits on all tracks and 500/640/844px viewports.');
}finally{if(browser)await browser.close();server.close()}})().catch(e=>{console.error(e);process.exitCode=1});
