// Visual geometry gates, independent of mission/game-state success.
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http');
const {chromium}=require('playwright');
(async()=>{const source=fs.readFileSync(process.env.RACER_TEST_SOURCE||path.join(__dirname,'../index.html'));const server=http.createServer((q,r)=>{r.setHeader('Content-Type','text/html;charset=utf-8');r.end(source)});await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;
try{browser=await chromium.launch({headless:true,...(process.env.TEST_BROWSER_PATH?{executablePath:process.env.TEST_BROWSER_PATH,args:['--no-sandbox','--disable-gpu','--disable-dev-shm-usage']}:{})});
for(const legacy of [false,true]){const p=await browser.newPage({viewport:{width:390,height:640},isMobile:true,hasTouch:true,deviceScaleFactor:3});const errors=[];p.on('pageerror',e=>errors.push(e.message));if(legacy)await p.addInitScript(()=>{window.ResizeObserver=undefined});await p.goto(`http://127.0.0.1:${server.address().port}`);await p.locator('#start').click();await p.waitForFunction(()=>document.getElementById('veil').hidden);
for(const size of [{width:390,height:640},{width:360,height:560},{width:390,height:844},{width:390,height:600},{width:320,height:500}]){await p.setViewportSize(size);await p.waitForTimeout(150);const g=await p.evaluate(()=>{const c=document.getElementById('game'),v=document.getElementById('view');const rect=e=>{const r=e.getBoundingClientRect();return{top:r.top,bottom:r.bottom,width:r.width,height:r.height}};const pixel=c.getContext('2d').getImageData(Math.floor(c.width/2),c.height-2,1,1).data;return{canvas:rect(c),view:rect(v),mission:rect(document.getElementById('missionHud')),deck:rect(document.querySelector('.touch-deck')),app:rect(document.querySelector('.app')),right:rect(document.getElementById('right')),innerHeight,scrollWidth:document.documentElement.scrollWidth,width:innerWidth,buffer:[c.width,c.height],pixel:[...pixel]}});
assert(g.canvas.top>=g.mission.bottom+4,'mission overlays the road');assert(Math.abs(g.canvas.bottom-g.view.bottom)<2,'blank strip below canvas');assert(Math.abs(g.deck.bottom-size.height)<2,'controls do not fill available viewport');assert(g.right.height>=64&&g.right.bottom<=size.height,'touch target clipped');assert(g.scrollWidth<=g.width,'horizontal overflow');assert(Math.abs(g.buffer[1]-g.canvas.height*1.25)<=1,'stale canvas drawing dimensions');assert(g.pixel[3]===255&&g.pixel[2]<=g.pixel[1]+5,'road not painted to bottom: '+JSON.stringify(g));assert(g.canvas.height>=190,'insufficient visible road');
if(process.env.QA_SHOTS&&size.width===390&&size.height===640)await p.screenshot({path:path.join(process.env.QA_SHOTS,`viewport-${legacy?'legacy':'modern'}.png`)});
}
await p.locator('#pause').click();assert(await p.locator('#resume').isVisible());await p.locator('#garage').click();await p.locator('#freeRide').click();await p.locator('#start').click();await p.waitForFunction(()=>document.getElementById('veil').hidden);assert(await p.locator('#missionHud').isHidden());assert.deepEqual(errors,[]);await p.close()}
console.log('PASS: 320–390px widths, 500–844px heights, live viewport shrink/grow, no ResizeObserver, no HUD/road overlap, no unpainted strip, visible controls and mode switch.');
}finally{if(browser)await browser.close();server.close()}})().catch(e=>{console.error(e);process.exitCode=1});
